version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nexus_chat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  chatserver:
    build: ./ChatServer
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=nexus_chat

  chatapp:
    build: ./ChatApp
    ports:
      - "3000:80"
    depends_on:
      - chatserver

volumes:
  pgdata:


